name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-docker-image .
    
    - name: check image
      run: docker images

    - name: Install Dockle
      run: |
        wget https://github.com/goodwithtech/dockle/releases/download/v0.4.1/dockle_0.4.1_Linux-64bit.tar.gz
        tar xvzf dockle_0.4.1_Linux-64bit.tar.gz
        sudo mv dockle /usr/local/bin/

    - name: Run Dockle
      run: dockle my-docker-image
