name: My Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        options:
        - production
        - staging
        - development
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to environment
        run: |
          if [ "${{ env.environment }}" == "production" ]; then
            echo "111111"
          elif [ "${{ env.environment }}" == "staging" ]; then
            deploy-to-staging.sh
          else
            echo "22222"
          fi
        env:
          ENVIRONMENT: ${{ env.environment }}
